import { useState } from 'react';
import { ActivityIndicator, Button, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useRoute } from '@react-navigation/native';
import { useAcknowledgeAlert, useAlerts, useReadings } from '../api/hooks';
import { MetricChart } from '../components/MetricChart';
import { useSessionStore } from '../state/session';
import { useSettingsStore } from '../state/settings';
import { thresholds, type AgeWeek } from '@kufuga/shared/thresholds';

export function DeviceDetailScreen(): React.JSX.Element {
  const route = useRoute<any>(); const token = useSessionStore((state) => state.accessToken); const [range, setRange] = useState<'24h' | '7d' | '30d'>('24h'); const settings = useSettingsStore(); const readings = useReadings(token, route.params.deviceId, range, range === '24h' ? 'hour' : 'day'); const alerts = useAlerts(token, Math.floor(Date.now() / 1000) - 30 * 86400); const acknowledge = useAcknowledgeAlert(token); const tempBand = thresholds[settings.birdType].temperatureC[settings.ageWeeks as AgeWeek];
  return <ScrollView style={styles.page}><Text style={styles.title}>{route.params.label}</Text><View style={styles.range}>{(['24h', '7d', '30d'] as const).map((item) => <Pressable key={item} style={[styles.rangeButton, range === item && styles.rangeActive]} onPress={() => setRange(item)}><Text style={range === item ? styles.rangeTextActive : styles.rangeText}>{item}</Text></Pressable>)}</View>{readings.isLoading ? <ActivityIndicator /> : <><Text style={styles.chartTitle}>Temperature</Text><MetricChart readings={readings.data ?? []} metric="tempC" minBand={tempBand.minC} maxBand={tempBand.maxC} color="#d97706" /><Text style={styles.chartTitle}>Humidity</Text><MetricChart readings={readings.data ?? []} metric="humidityPct" minBand={45} maxBand={75} color="#2563eb" /><Text style={styles.chartTitle}>Ammonia (NH3)</Text><MetricChart readings={readings.data ?? []} metric="nh3Ppm" minBand={0} maxBand={15} color="#c53030" /></>}<Text style={styles.section}>Alert history</Text>{(alerts.data ?? []).filter((alert) => alert.deviceId === route.params.deviceId).map((alert) => <View key={alert.id} style={styles.alert}><View style={{ flex: 1 }}><Text style={styles.alertKind}>{alert.kind.replaceAll('_', ' ')}</Text><Text>{alert.value.toFixed(1)} · {new Date(alert.ts * 1000).toLocaleString()}</Text></View>{alert.acknowledged ? <Text style={styles.ack}>Acknowledged</Text> : <Button title="Acknowledge" onPress={() => acknowledge.mutate(alert.id)} />}</View>)}</ScrollView>;
}
const styles = StyleSheet.create({ page: { backgroundColor: '#f6faf8', flex: 1, padding: 16 }, title: { color: '#173b2d', fontSize: 28, fontWeight: '800', marginBottom: 14 }, range: { flexDirection: 'row', gap: 8, marginBottom: 18 }, rangeButton: { borderColor: '#b9d6c7', borderRadius: 18, borderWidth: 1, paddingHorizontal: 16, paddingVertical: 8 }, rangeActive: { backgroundColor: '#176b4d' }, rangeText: { color: '#176b4d' }, rangeTextActive: { color: '#fff' }, chartTitle: { color: '#365247', fontSize: 17, fontWeight: '700', marginTop: 10 }, section: { borderTopColor: '#dce9e2', borderTopWidth: 1, color: '#173b2d', fontSize: 21, fontWeight: '800', marginTop: 20, paddingTop: 18 }, alert: { alignItems: 'center', backgroundColor: '#fff', borderRadius: 10, flexDirection: 'row', marginTop: 10, padding: 12 }, alertKind: { fontWeight: '700' }, ack: { color: '#198754', fontSize: 12, fontWeight: '700' } });
