import { Button, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useFarm } from '../api/hooks';
import { useSessionStore } from '../state/session';
import { useSettingsStore } from '../state/settings';

export function SettingsScreen(): React.JSX.Element {
  const token = useSessionStore((state) => state.accessToken); const farmId = useSessionStore((state) => state.user?.farmId ?? null); const farm = useFarm(token, farmId); const logout = useSessionStore((state) => state.logout); const settings = useSettingsStore();
  return <ScrollView style={styles.page}><Text style={styles.title}>Settings</Text><Text style={styles.section}>Farm profile</Text>{farm.data && <View style={styles.card}><Text style={styles.big}>{farm.data.ownerName}</Text><Text>{farm.data.region} · {farm.data.flockSize} birds</Text><Text>{farm.data.phone}</Text></View>}<Text style={styles.section}>Threshold profile</Text><Text style={styles.label}>Bird type</Text><View style={styles.row}>{(['broiler', 'layer'] as const).map((type) => <Pressable key={type} style={[styles.choice, settings.birdType === type && styles.selected]} onPress={() => settings.setBirdType(type)}><Text style={settings.birdType === type ? styles.selectedText : undefined}>{type}</Text></Pressable>)}</View><Text style={styles.label}>Flock age: week {settings.ageWeeks}</Text><View style={styles.row}>{[1, 2, 3, 4, 5, 6].map((week) => <Pressable key={week} style={[styles.age, settings.ageWeeks === week && styles.selected]} onPress={() => settings.setAgeWeeks(week as 1 | 2 | 3 | 4 | 5 | 6)}><Text style={settings.ageWeeks === week ? styles.selectedText : undefined}>{week}</Text></Pressable>)}</View><Text style={styles.section}>Language</Text><View style={styles.row}>{[['en', 'English'], ['sw', 'Swahili'], ['tw', 'Twi']].map(([code, label]) => <Pressable key={code} style={[styles.choice, settings.language === code && styles.selected]} onPress={() => settings.setLanguage(code as 'en' | 'sw' | 'tw')}><Text style={settings.language === code ? styles.selectedText : undefined}>{label}</Text></Pressable>)}</View><Text style={styles.stub}>Swahili and Twi translations are prepared here for a future release.</Text><View style={{ marginTop: 24 }}><Button title="Log out" onPress={logout} /></View></ScrollView>;
}
const styles = StyleSheet.create({ page: { backgroundColor: '#f6faf8', flex: 1, padding: 16 }, title: { color: '#173b2d', fontSize: 28, fontWeight: '800' }, section: { color: '#173b2d', fontSize: 20, fontWeight: '800', marginBottom: 10, marginTop: 24 }, card: { backgroundColor: '#fff', borderRadius: 12, gap: 6, padding: 16 }, big: { fontSize: 21, fontWeight: '700' }, label: { color: '#52635b', fontSize: 16, marginBottom: 8 }, row: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, choice: { borderColor: '#b9d6c7', borderRadius: 18, borderWidth: 1, paddingHorizontal: 15, paddingVertical: 9 }, age: { alignItems: 'center', borderColor: '#b9d6c7', borderRadius: 18, borderWidth: 1, height: 38, justifyContent: 'center', width: 38 }, selected: { backgroundColor: '#176b4d' }, selectedText: { color: '#fff' }, stub: { color: '#6b7d74', fontSize: 14, marginTop: 10 } });
