'use client';

import { useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, LogOut, Radio, WifiOff } from 'lucide-react';
import { useState } from 'react';
import { api, type Alert, type Farm, type FleetRow } from '../lib/api';
import { Badge, Button, Card, Input, Table } from './ui';
import { DeviceCharts } from './device-charts';

async function getSession(): Promise<{ authenticated: boolean }> {
  const response = await fetch('/api/auth/session');
  return response.json() as Promise<{ authenticated: boolean }>;
}

function Login() {
  const client = useQueryClient();
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(''); const response = await fetch('/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password }) }); if (!response.ok) { setError('Invalid admin credentials'); return; } await client.invalidateQueries({ queryKey: ['session'] }); }
  return <main className="flex min-h-screen items-center justify-center p-6"><Card className="w-full max-w-md"><div className="mb-8"><div className="text-3xl font-black text-moss">Kufuga</div><p className="mt-2 text-slate-500">Operations console</p></div><form className="space-y-4" onSubmit={submit}><label className="block text-sm font-medium">Email<Input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-1" /></label><label className="block text-sm font-medium">Password<Input required type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="mt-1" /></label>{error && <p className="text-sm text-red-600">{error}</p>}<Button className="w-full" type="submit">Sign in</Button></form></Card></main>;
}

function FleetTable({ rows, onSelect }: { rows: FleetRow[]; onSelect: (row: FleetRow) => void }) { return <Table><thead><tr className="border-b border-line text-xs uppercase text-slate-500"><th className="p-3">Device</th><th className="p-3">Farm</th><th className="p-3">Latest</th><th className="p-3">Alerts</th><th className="p-3">Status</th></tr></thead><tbody>{rows.map((row) => { const offline = !row.latest || Date.now() / 1000 - row.latest.ts > 1800; return <tr key={row.device.id} className="cursor-pointer border-b border-line/70 hover:bg-mint" onClick={() => onSelect(row)}><td className="p-3 font-semibold">{row.device.label}<div className="text-xs font-normal text-slate-500">{row.device.country}</div></td><td className="p-3">{row.farm.region}</td><td className="p-3">{row.latest ? `${row.latest.tempC.toFixed(1)}°C · ${row.latest.nh3Ppm.toFixed(0)}ppm NH3` : 'No data'}</td><td className="p-3">{row.alertCount}</td><td className="p-3">{offline ? <Badge tone="red"><WifiOff className="mr-1 h-3 w-3" /> Offline</Badge> : row.latest?.alert ? <Badge tone="amber"><AlertTriangle className="mr-1 h-3 w-3" /> Alert</Badge> : <Badge tone="green">Online</Badge>}</td></tr>; })}</tbody></Table>; }

function ProvisionForm({ farms }: { farms: Farm[] }) { const [form, setForm] = useState({ farmId: farms[0]?.id ?? '', label: '', simNumber: '', country: 'KE' }); const [result, setResult] = useState(''); async function submit(event: React.FormEvent) { event.preventDefault(); const response = await api<{ mqtt: { username: string; password: string }; device: { label: string } }>('/admin/devices', { method: 'POST', body: JSON.stringify(form) }); setResult(`${response.device.label}: ${response.mqtt.username} / ${response.mqtt.password}`); } return <Card><h2 className="mb-4 text-lg font-bold">Provision device</h2><form className="grid gap-3 md:grid-cols-4" onSubmit={submit}><select className="rounded-lg border border-line px-3 py-2" value={form.farmId} onChange={(event) => setForm({ ...form, farmId: event.target.value })}>{farms.map((farm) => <option key={farm.id} value={farm.id}>{farm.ownerName} · {farm.region}</option>)}</select><Input required placeholder="House label" value={form.label} onChange={(event) => setForm({ ...form, label: event.target.value })} /><Input required placeholder="SIM number" value={form.simNumber} onChange={(event) => setForm({ ...form, simNumber: event.target.value })} /><Button type="submit">Issue credentials</Button></form>{result && <p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Save once — MQTT credentials: <strong>{result}</strong></p>}</Card>; }

function AlertsFeed({ alerts }: { alerts: Alert[] }) { const [filter, setFilter] = useState('all'); const visible = alerts.filter((alert) => filter === 'all' || alert.kind === filter); return <Card><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-bold">Alerts feed</h2><select className="rounded-lg border border-line px-3 py-2 text-sm" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">All conditions</option><option value="NH3_DANGER">NH3 danger</option><option value="TEMP_HIGH">Temperature high</option><option value="DEVICE_OFFLINE">Device offline</option></select></div><div className="space-y-2">{visible.slice(0, 30).map((alert) => <div key={alert.id} className="flex items-center justify-between rounded-lg bg-slate-50 p-3"><div><div className="font-semibold">{alert.kind.replaceAll('_', ' ')}</div><div className="text-xs text-slate-500">{new Date(alert.ts * 1000).toLocaleString()} · {alert.value.toFixed(1)}</div></div><Badge tone={alert.acknowledged ? 'green' : 'red'}>{alert.acknowledged ? 'Acknowledged' : 'Open'}</Badge></div>)}</div></Card>; }

export function AdminConsole() {
  const session = useQuery({ queryKey: ['session'], queryFn: getSession }); const [section, setSection] = useState<'fleet' | 'farms' | 'alerts'>('fleet'); const [selected, setSelected] = useState<FleetRow | null>(null);
  const enabled = Boolean(session.data?.authenticated); const fleet = useQuery({ queryKey: ['fleet'], queryFn: () => api<FleetRow[]>('/admin/fleet'), enabled, refetchInterval: 30_000 }); const farms = useQuery({ queryKey: ['admin-farms'], queryFn: () => api<Farm[]>('/admin/farms'), enabled }); const alerts = useQuery({ queryKey: ['admin-alerts'], queryFn: () => api<Alert[]>('/alerts?since=0'), enabled, refetchInterval: 30_000 });
  if (session.isLoading) return <div className="p-10 text-slate-500">Loading session…</div>; if (!enabled) return <Login />;
  async function logout() { await fetch('/api/auth/logout', { method: 'POST' }); await session.refetch(); }
  return <div className="min-h-screen"><header className="border-b border-line bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><div><div className="text-2xl font-black text-moss">Kufuga</div><div className="text-xs text-slate-500">Operations console</div></div><div className="flex items-center gap-4"><a className="text-sm text-moss hover:underline" href="/investors">Investor view</a><Button className="flex items-center gap-2 bg-slate-700" onClick={logout}><LogOut className="h-4 w-4" /> Sign out</Button></div></div></header><main className="mx-auto max-w-7xl space-y-6 px-6 py-8"><div className="grid gap-4 md:grid-cols-3"><Card><div className="text-sm text-slate-500">Fleet devices</div><div className="mt-2 text-3xl font-black">{fleet.data?.length ?? '—'}</div></Card><Card><div className="text-sm text-slate-500">Open alerts</div><div className="mt-2 text-3xl font-black text-red-600">{alerts.data?.filter((alert) => !alert.acknowledged).length ?? '—'}</div></Card><Card><div className="text-sm text-slate-500">API status</div><div className="mt-2 flex items-center gap-2 text-lg font-bold text-emerald-700"><Radio className="h-5 w-5" /> Live polling</div></Card></div><nav className="flex gap-2 border-b border-line"><button className={section === 'fleet' ? 'border-b-2 border-moss px-4 py-3 font-bold text-moss' : 'px-4 py-3 text-slate-500'} onClick={() => setSection('fleet')}>Fleet</button><button className={section === 'farms' ? 'border-b-2 border-moss px-4 py-3 font-bold text-moss' : 'px-4 py-3 text-slate-500'} onClick={() => setSection('farms')}>Farms & devices</button><button className={section === 'alerts' ? 'border-b-2 border-moss px-4 py-3 font-bold text-moss' : 'px-4 py-3 text-slate-500'} onClick={() => setSection('alerts')}>Alerts</button></nav>{section === 'fleet' && <><Card><h1 className="mb-4 text-xl font-bold">Live fleet</h1><FleetTable rows={fleet.data ?? []} onSelect={setSelected} /></Card>{selected && <DeviceCharts deviceId={selected.device.id} label={selected.device.label} />}</>}{section === 'farms' && <ProvisionForm farms={farms.data ?? []} />}{section === 'alerts' && <AlertsFeed alerts={alerts.data ?? []} />}</main></div>;
}
