'use client';
import { useQuery } from '@tanstack/react-query';
import { Download } from 'lucide-react';
import { useMemo } from 'react';
import { api, type Reading } from '../lib/api';
import { Button, Card } from './ui';
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

export function DeviceCharts({ deviceId, label }: { deviceId: string; label: string }) { const readings = useQuery({ queryKey: ['web-readings', deviceId], queryFn: () => api<Reading[]>(`/devices/${deviceId}/readings?from=${Math.floor(Date.now() / 1000) - 86400 * 30}&to=${Math.floor(Date.now() / 1000)}&resolution=day`) }); const data = useMemo(() => (readings.data ?? []).map((row) => ({ ...row, time: new Date(row.ts * 1000).toLocaleDateString() })), [readings.data]); const download = () => { const csv = ['ts,tempC,humidityPct,nh3Ppm,alert', ...(readings.data ?? []).map((row) => `${row.ts},${row.tempC},${row.humidityPct},${row.nh3Ppm},${row.alert}`)].join('\n'); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); const link = document.createElement('a'); link.href = url; link.download = `${label.replaceAll(' ', '-')}-readings.csv`; link.click(); URL.revokeObjectURL(url); }; return <Card><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-bold">{label} · 30-day trend</h2><p className="text-sm text-slate-500">Raw data export available for audits</p></div><Button className="flex items-center gap-2 bg-slate-700" onClick={download}><Download className="h-4 w-4" /> CSV</Button></div><div className="h-72 w-full">{readings.isLoading ? <div className="p-8 text-slate-500">Loading readings…</div> : <ResponsiveContainer><LineChart data={data}><CartesianGrid strokeDasharray="3 3" stroke="#dce9e2" /><XAxis dataKey="time" /><YAxis /><Tooltip /><Legend /><Line type="monotone" dataKey="tempC" name="Temp °C" stroke="#d97706" dot={false} /><Line type="monotone" dataKey="humidityPct" name="Humidity %" stroke="#2563eb" dot={false} /><Line type="monotone" dataKey="nh3Ppm" name="NH3 ppm" stroke="#c53030" dot={false} /></LineChart></ResponsiveContainer>}</div></Card>; }
